defmodule AshUpdateUnloadCheck.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:authors) do
      add(:state, :text, null: false, default: "active")
    end
  end

  def down do
    alter table(:authors) do
      remove(:state)
    end
  end
end
