defmodule AshUpdateUnloadCheck.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add(:published, :boolean, default: true)
    end
  end

  def down do
    alter table(:posts) do
      remove(:published)
    end
  end
end
