defmodule AshUpdateUnloadCheck.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:authors) do
      add(:birthday, :date)
    end
  end

  def down do
    alter table(:authors) do
      remove(:birthday)
    end
  end
end
