defmodule AshUpdateUnloadCheck.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add(:archived_at, :utc_datetime_usec)
    end

    alter table(:authors) do
      add(:archived_at, :utc_datetime_usec)
    end
  end

  def down do
    alter table(:authors) do
      remove(:archived_at)
    end

    alter table(:posts) do
      remove(:archived_at)
    end
  end
end
