defmodule AshUpdateUnloadCheck.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:posts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text)
      add(:author_id, :uuid)
    end

    create table(:authors, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:posts) do
      modify(
        :author_id,
        references(:authors,
          column: :id,
          name: "posts_author_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:authors) do
      add(:first_name, :text)
      add(:last_name, :text)
    end
  end

  def down do
    alter table(:authors) do
      remove(:last_name)
      remove(:first_name)
    end

    drop(constraint(:posts, "posts_author_id_fkey"))

    alter table(:posts) do
      modify(:author_id, :uuid)
    end

    drop(table(:authors))

    drop(table(:posts))
  end
end
